//以下参数仅符合我的个人手感，仅供参考
#define PERMISSIVE_HOLD
#define TAPPING_TERM 160
#define QUICK_TAP_TERM 0
#define COMBO_TERM 20
#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define MOUSEKEY_DELAY 5
#define MOUSEKEY_INTERVAL 5
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_MAX_SPEED 22
#define MOUSEKEY_TIME_TO_MAX 82

#define MOUSEKEY_WHEEL_DELAY 8
#define MOUSEKEY_WHEEL_INTERVAL 65
#define MOUSEKEY_WHEEL_DELTA 0.5
#define MOUSEKEY_WHEEL_MAX_SPEED 18
#define MOUSEKEY_WHEEL_TIME_TO_MAX 42